dist: xenial
services:
  - xvfb
addons:
  chrome: stable

language: node_js
node_js:
  - "node"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

script:
  - npm run test
  - npm run test:e2e
  - npm run test:firefox
  
