dist: xenial
services:
  - xvfb
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "node"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

script: xvfb-run yarn test