dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  firefox: stable

language: node_js
node_js:
  - "node"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome

script:
  - npm test
  - npm run test:e2e:chrome
#  - npm run test:e2e:firefox
