name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm run lint
    - run: npm run lint:style

  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: xvfb-run --auto-servernum npm test

  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm run test:e2e:chrome:headless
